### ISSUE TITLE
Decoding support (Bufany)

### ISSUE THREAD

**Issue by webmaster128** [noislabs/anybuf#11]
- [x] SliceReader (#2)
- [x] Varint decoding (#2)
- [x] Fixed decoding (#2)
- [x] variable length decoding (#2)
- [x] uint32/uint64 accessors (#2)
- [x] sint32/sint64 accessors (#2)
- [x] int32/int64 accessors (#14)
- [x] boolean accessors (#2)
- [x] repeated support
    - [x] repeated_string (#2)
    - [x] repeated_bytes (#2)
    - [x] repeated_uint32/repeated_uint64 (#2)
    - [x] repeated_bool (#2)
    - [x] repeated_sint32/repeated_sint64 (#2)
    - [x] repeated_int32/repeated_int64 (#14)
    - [x] repeated message (#24)
- [x] nested messages support (#2)
- [x] read limit in `read_unsigned_varint` (#2)

**Comment by webmaster128** [comment]
All done here 🦾
